### ISSUE TITLE
Incorporate changes from prologic/billmonger

### ISSUE THREAD

**Issue by prologic** [relistan/billmonger#6]
Hi! Thanks for writing this very nice tool! I use it to send invoices to the company I work for now and it's pretty awesome! I did however have to make some modifications in my [fork](https://github.com/prologic/billmonger) that I'd love for you to take a look as ways to improve the flexibility of your project so perhaps one day I can drop my fork :)

**Comment by relistan** [comment]
Hey @prologic thanks, glad you like it! I am sorry for the slow response here. I'll take a look over the weekend. Cheers.

**Comment by prologic** [comment]
No worries. I use your software (_forked_) to bill the company I work for. I currently cannot use your version as I needed some modifications to make it work for me needs :)

**Comment by relistan** [comment]
Repo was deleted

**Comment by prologic** [comment]
> Repo was deleted

Ahh sorry, it got moved to https://git.mills.io/prologic/billmonger
